from pathlib import Path

p = Path('instrument_product_guide.py')
s = p.read_text(encoding='utf-8')
marker = '\ndef render_product_guide_hub():'
pos = s.find(marker)
if pos < 0:
    raise SystemExit('render_product_guide_hub not found')

# Keep the legacy module import-compatible because older adapters may still
# import render_product_guide_hub, but render nothing. The official 19-page
# guide is generated by instrument_product_guide_pdf.py and rendered from
# instrument_v03_user_guide.py.
replacement = '''\ndef render_product_guide_hub():
    \"\"\"Legacy 21-page guide UI retired.

    Kept as a no-op for backward compatibility with older adapters/imports.
    The application exposes only the official 19-page Product & User Guide.
    \"\"\"
    return None
'''

s = s[:pos] + replacement
p.write_text(s, encoding='utf-8')
print('legacy 21-page product guide hub disabled')
