from pathlib import Path

# 1) Add a template-compatible exporter beside the strict Excel importer.
guide = Path('instrument_v03_user_guide.py')
s = guide.read_text(encoding='utf-8')
anchor = '''def _render_excel_import():\n'''
if 'def _excel_export_bytes(' not in s:
    helper = '''def _excel_export_bytes(instruments):\n    \"\"\"Export the current registry using the exact import-template headers.\n\n    This makes the downloaded registry round-trip compatible with the controlled\n    bulk importer: users can export, update approved fields, preview, then\n    re-import without manual header remapping.\n    \"\"\"\n    columns = list(V03_EXCEL_FIELD_MAP.keys())\n    rows = []\n    for inst in instruments or []:\n        row = {}\n        for header, db_field in V03_EXCEL_FIELD_MAP.items():\n            value = inst.get(db_field)\n            if header in V03_EXCEL_BOOL_FIELDS and value is not None:\n                value = \"Yes\" if bool(value) else \"No\"\n            row[header] = \"\" if value is None else value\n        rows.append(row)\n\n    output = BytesIO()\n    with pd.ExcelWriter(output, engine=\"openpyxl\") as writer:\n        pd.DataFrame(rows, columns=columns).to_excel(writer, index=False, sheet_name=\"Instruments\")\n        ws = writer.book[\"Instruments\"]\n        ws.freeze_panes = \"A2\"\n        ws.auto_filter.ref = ws.dimensions\n        for cell in ws[1]:\n            cell.font = cell.font.copy(bold=True)\n        for column_cells in ws.columns:\n            max_len = max((len(str(c.value)) if c.value is not None else 0) for c in column_cells)\n            ws.column_dimensions[column_cells[0].column_letter].width = min(max(max_len + 2, 12), 32)\n\n        pd.DataFrame([\n            [\"Purpose\", \"Current instrument registry exported with the exact controlled import headers.\"],\n            [\"Round trip\", \"You may update approved fields in this workbook, then upload it through Instruments → Import Instrument List.\"],\n            [\"Evidence rule\", \"Do not fill unknown or missing evidence by assumption. Leave unavailable evidence blank.\"],\n            [\"History\", \"Maintenance, calibration event history, failures and investigations remain in their dedicated modules and are not replaced by this registry export.\"],\n        ], columns=[\"Item\", \"Instruction\"]).to_excel(writer, index=False, sheet_name=\"Read Me\")\n    output.seek(0)\n    return output.getvalue()\n\n\n'''
    if anchor not in s:
        raise SystemExit('guide anchor not found')
    s = s.replace(anchor, helper + anchor, 1)
    guide.write_text(s, encoding='utf-8')

# 2) Upgrade Current Instrument Registry with export + mobile-friendly search/filter.
core = Path('instrument_supabase_app.py')
c = core.read_text(encoding='utf-8')
old = '''        with st.expander("📋 سجل الأجهزة الحالي | Current Instrument Registry", expanded=False):\n            registry_rows = [{\n                "Instrument ID": x.get("instrument_code") or "",\n                "Instrument name": x.get("instrument_name") or "",\n                "Type": x.get("instrument_type") or "",\n                "Manufacturer": x.get("manufacturer") or "",\n                "Model": x.get("model") or "",\n                "Location": x.get("location") or "",\n                "Status": x.get("operational_status") or "",\n            } for x in instruments]\n            st.dataframe(pd.DataFrame(registry_rows), use_container_width=True, hide_index=True)\n'''
new = '''        with st.expander("📋 سجل الأجهزة الحالي | Current Instrument Registry", expanded=False):\n            st.caption("Search the live registry, then export the complete current list in the same controlled format used by Import Instrument List.")\n            registry_rows = [{\n                "Instrument ID": x.get("instrument_code") or "",\n                "Instrument name": x.get("instrument_name") or "",\n                "Type": x.get("instrument_type") or "",\n                "Manufacturer": x.get("manufacturer") or "",\n                "Model": x.get("model") or "",\n                "Location": x.get("location") or "",\n                "Status": x.get("operational_status") or "",\n            } for x in instruments]\n            registry_df = pd.DataFrame(registry_rows)\n\n            if callable(globals().get("_excel_export_bytes")):\n                st.download_button(\n                    "⬇️ Download Current Instrument List (.xlsx)",\n                    data=_excel_export_bytes(instruments),\n                    file_name="Yahia_QC_Current_Instrument_Registry.xlsx",\n                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",\n                    use_container_width=True,\n                    key="download_current_instrument_registry",\n                )\n                st.caption("Template-compatible export: edit approved fields, then preview and re-upload through Import Instrument List when needed.")\n\n            q = st.text_input(\n                "Search registry",\n                placeholder="Instrument ID, name, model, manufacturer, location…",\n                key="instrument_registry_search",\n            ).strip().lower()\n            status_values = sorted([str(v) for v in registry_df["Status"].dropna().unique() if str(v).strip()])\n            selected_statuses = st.multiselect(\n                "Status filter",\n                status_values,\n                default=[],\n                key="instrument_registry_status_filter",\n            )\n\n            filtered_df = registry_df.copy()\n            if q:\n                mask = filtered_df.astype(str).apply(\n                    lambda col: col.str.lower().str.contains(q, regex=False)\n                ).any(axis=1)\n                filtered_df = filtered_df[mask]\n            if selected_statuses:\n                filtered_df = filtered_df[filtered_df["Status"].isin(selected_statuses)]\n\n            st.caption(f"Showing {len(filtered_df)} of {len(registry_df)} instruments")\n            st.dataframe(filtered_df, use_container_width=True, hide_index=True)\n'''
if old not in c:
    raise SystemExit('registry block anchor not found')
c = c.replace(old, new, 1)
core.write_text(c, encoding='utf-8')
print('instrument registry upgraded with controlled export and search/filter')
